import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowDownLeft, ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, CreditCard, Edit3, Filter, Landmark, LayoutDashboard, MoreHorizontal, PiggyBank, Plus, Receipt, Search, Settings, Sparkles, Trash2, TrendingUp, Wallet, X } from 'lucide-react'

type TxType = 'income' | 'expense'
type Range = 'week' | 'month' | 'year' | 'custom'
type Transaction = { id: string; date: string; type: TxType; amount: number; category: string; account: string; description: string; recurring: boolean }
type Budget = { category: string; limit: number }

const categories = ['Housing', 'Food', 'Transport', 'Bills', 'Health', 'Entertainment', 'Shopping', 'Salary', 'Freelance', 'Investments', 'Other']
const expenseCategories = categories.filter(c => !['Salary', 'Freelance', 'Investments'].includes(c))
const categoryColors: Record<string, string> = { Housing: '#7c6cf2', Food: '#f59e0b', Transport: '#22c55e', Bills: '#ef6b6b', Health: '#e879f9', Entertainment: '#38bdf8', Shopping: '#fb7185', Other: '#94a3b8' }
const accounts = ['Cash', 'Checking', 'Savings', 'Credit Card']
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n)
const today = new Date().toISOString().slice(0, 10)
const iso = (daysAgo: number) => { const d = new Date(); d.setDate(d.getDate() - daysAgo); return d.toISOString().slice(0, 10) }

const seedTransactions: Transaction[] = [
  { id: '1', date: iso(1), type: 'expense', amount: 84.2, category: 'Food', account: 'Checking', description: 'Sunday market', recurring: false },
  { id: '2', date: iso(2), type: 'income', amount: 4200, category: 'Salary', account: 'Checking', description: 'Acme Corp · Monthly salary', recurring: true },
  { id: '3', date: iso(4), type: 'expense', amount: 1450, category: 'Housing', account: 'Checking', description: 'Apartment rent', recurring: true },
  { id: '4', date: iso(6), type: 'expense', amount: 62.4, category: 'Transport', account: 'Credit Card', description: 'Gas & parking', recurring: false },
  { id: '5', date: iso(8), type: 'expense', amount: 129, category: 'Bills', account: 'Checking', description: 'Electric + internet', recurring: true },
  { id: '6', date: iso(10), type: 'income', amount: 680, category: 'Freelance', account: 'Savings', description: 'Brand identity project', recurring: false },
  { id: '7', date: iso(13), type: 'expense', amount: 210, category: 'Shopping', account: 'Credit Card', description: 'Winter essentials', recurring: false },
  { id: '8', date: iso(17), type: 'expense', amount: 49, category: 'Entertainment', account: 'Credit Card', description: 'Streaming subscriptions', recurring: true },
  { id: '9', date: iso(21), type: 'expense', amount: 86, category: 'Health', account: 'Checking', description: 'Pharmacy', recurring: false },
]
const seedBudgets: Budget[] = [{ category: 'Housing', limit: 1600 }, { category: 'Food', limit: 500 }, { category: 'Transport', limit: 250 }, { category: 'Bills', limit: 300 }, { category: 'Entertainment', limit: 150 }]

function App() {
  const [transactions, setTransactions] = useState<Transaction[]>(() => JSON.parse(localStorage.getItem('ledgerly-transactions') || 'null') || seedTransactions)
  const [budgets, setBudgets] = useState<Budget[]>(() => JSON.parse(localStorage.getItem('ledgerly-budgets') || 'null') || seedBudgets)
  const [active, setActive] = useState('Overview')
  const [range, setRange] = useState<Range>('month')
  const [query, setQuery] = useState('')
  const [typeFilter, setTypeFilter] = useState<'all' | TxType>('all')
  const [modal, setModal] = useState<'transaction' | 'budget' | null>(null)
  const [editing, setEditing] = useState<Transaction | null>(null)
  const [confirmDelete, setConfirmDelete] = useState<Transaction | null>(null)

  useEffect(() => { localStorage.setItem('ledgerly-transactions', JSON.stringify(transactions)) }, [transactions])
  useEffect(() => { localStorage.setItem('ledgerly-budgets', JSON.stringify(budgets)) }, [budgets])

  const filtered = useMemo(() => transactions.filter(t => {
    const text = `${t.description} ${t.category} ${t.account}`.toLowerCase()
    const d = new Date(t.date)
    const now = new Date()
    const inRange = range === 'year' ? d.getFullYear() === now.getFullYear() : range === 'week' ? (now.getTime() - d.getTime()) <= 7 * 86400000 : range === 'month' ? d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear() : true
    return inRange && text.includes(query.toLowerCase()) && (typeFilter === 'all' || t.type === typeFilter)
  }).sort((a, b) => b.date.localeCompare(a.date)), [transactions, range, query, typeFilter])
  const income = filtered.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0)
  const expenses = filtered.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0)
  const balance = transactions.reduce((s, t) => s + (t.type === 'income' ? t.amount : -t.amount), 0) + 12400
  const savings = income ? Math.round(((income - expenses) / income) * 100) : 0

  const cashFlow = useMemo(() => Array.from({ length: 6 }, (_, i) => { const d = new Date(); d.setMonth(d.getMonth() - 5 + i); const label = d.toLocaleString('en-US', { month: 'short' }); const monthTx = transactions.filter(t => { const td = new Date(t.date); return td.getMonth() === d.getMonth() && td.getFullYear() === d.getFullYear() }); return { name: label, income: monthTx.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0), expenses: monthTx.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0) } }), [transactions])
  const breakdown = expenseCategories.map(category => ({ name: category, value: filtered.filter(t => t.type === 'expense' && t.category === category).reduce((s, t) => s + t.amount, 0) })).filter(x => x.value > 0)
  const accountBalances = accounts.map(account => ({ name: account, amount: 0, icon: account === 'Credit Card' ? CreditCard : account === 'Savings' ? PiggyBank : account === 'Checking' ? Landmark : Wallet })).map(a => ({ ...a, amount: (a.name === 'Cash' ? 820 : a.name === 'Checking' ? 6420 : a.name === 'Savings' ? 9350 : -780) + transactions.filter(t => t.account === a.name).reduce((s, t) => s + (t.type === 'income' ? t.amount : -t.amount), 0) }))

  const saveTransaction = (tx: Transaction) => { setTransactions(prev => editing ? prev.map(t => t.id === editing.id ? tx : t) : [tx, ...prev]); setModal(null); setEditing(null) }
  const deleteTransaction = () => { if (confirmDelete) setTransactions(prev => prev.filter(t => t.id !== confirmDelete.id)); setConfirmDelete(null) }
  const openNew = () => { setEditing(null); setModal('transaction') }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>ledgerly</span></div><div className="workspace"><div className="avatar">JD</div><div><strong>Jordan Davis</strong><small>Personal workspace</small></div><ChevronDown size={15} /></div><nav><p className="nav-label">Workspace</p>{[['Overview', LayoutDashboard], ['Transactions', Receipt], ['Budgets', PiggyBank], ['Accounts', Wallet]].map(([name, Icon]) => <button className={active === name ? 'nav-item active' : 'nav-item'} onClick={() => setActive(name as string)} key={name as string}><Icon size={17} />{name as string}</button>)}<p className="nav-label second">Manage</p><button className="nav-item"><CalendarDays size={17} />Recurring</button><button className="nav-item"><Settings size={17} />Settings</button></nav><div className="upgrade"><div className="upgrade-icon"><Sparkles size={15} /></div><strong>Stay on track</strong><p>Your spending is down 12% this month. Keep it up!</p><button onClick={() => setActive('Budgets')}>View insights <ArrowUpRight size={14} /></button></div><div className="sidebar-footer"><div className="mini-avatar">JD</div><div><strong>Jordan Davis</strong><small>Free plan</small></div><MoreHorizontal size={17} /></div></aside>
    <main className="main-content"><header className="topbar"><div className="mobile-brand"><div className="brand-mark"><Sparkles size={17} /></div>ledgerly</div><div className="breadcrumb">Workspace <span>/</span> <b>{active}</b></div><div className="top-actions"><button className="icon-button notification"><Bell size={18} /><i /></button><div className="top-avatar">JD</div></div></header>
      {active === 'Overview' ? <><section className="page-heading"><div><p className="eyebrow">{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p><h1>Good morning, Jordan <span>✦</span></h1><p className="subheading">Here’s your financial overview.</p></div><button className="primary-button" onClick={openNew}><Plus size={17} /> Add transaction</button></section>
      <div className="range-row"><div className="range-tabs">{(['week', 'month', 'year', 'custom'] as Range[]).map(r => <button className={range === r ? 'selected' : ''} onClick={() => setRange(r)} key={r}>{r === 'custom' ? 'Custom range' : `This ${r}`}</button>)}</div><div className="range-actions"><button className="filter-button" onClick={() => setTypeFilter(typeFilter === 'all' ? 'expense' : typeFilter === 'expense' ? 'income' : 'all')}><Filter size={15} /> {typeFilter === 'all' ? 'Filter' : typeFilter}</button><div className="search-box"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search transactions" /></div></div></div>
      <section className="stat-grid"><Stat title="Current balance" value={money(balance)} detail="Across all accounts" icon={<Wallet />} tone="purple" /><Stat title="Total income" value={money(income)} detail="Compared to last month" change="+8.4%" icon={<ArrowDownLeft />} tone="green" /><Stat title="Total expenses" value={money(expenses)} detail="Compared to last month" change="-12.1%" icon={<ArrowUpRight />} tone="red" /><Stat title="Savings rate" value={`${savings}%`} detail="Target is 30%" change={savings >= 30 ? 'On track' : 'Below target'} icon={<TrendingUp />} tone="blue" /></section>
      <section className="dashboard-grid"><div className="card cashflow-card"><CardHeading title="Cash flow" subtitle="Income vs. expenses" action="Last 6 months" /><div className="chart-legend"><span><i className="dot income-dot" /> Income</span><span><i className="dot expense-dot" /> Expenses</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={cashFlow} margin={{ top: 8, right: 4, left: -20, bottom: 0 }}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#22c55e" stopOpacity={.18}/><stop offset="95%" stopColor="#22c55e" stopOpacity={0}/></linearGradient><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#ef6b6b" stopOpacity={.15}/><stop offset="95%" stopColor="#ef6b6b" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#edf0f3"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#98a1ad', fontSize: 12 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: '#98a1ad', fontSize: 11 }} tickFormatter={v => `$${v/1000}k`}/><Tooltip formatter={(v: number) => money(v)} contentStyle={{ border: 0, borderRadius: 10, boxShadow: '0 8px 24px #17203318' }}/><Area type="monotone" dataKey="income" stroke="#22c55e" strokeWidth={2.5} fill="url(#incomeFill)"/><Area type="monotone" dataKey="expenses" stroke="#ef6b6b" strokeWidth={2.5} fill="url(#expenseFill)"/></AreaChart></ResponsiveContainer></div></div>
      <div className="card breakdown-card"><CardHeading title="Spending breakdown" subtitle="By category" action="This month" /><div className="pie-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={breakdown} dataKey="value" nameKey="name" innerRadius={63} outerRadius={87} paddingAngle={3} stroke="none">{breakdown.map(entry => <Cell key={entry.name} fill={categoryColors[entry.name] || '#94a3b8'} />)}</Pie><Tooltip formatter={(v: number) => money(v)} /></PieChart></ResponsiveContainer><div className="pie-center"><strong>{money(expenses)}</strong><span>Spent</span></div></div><div className="category-list">{breakdown.slice(0, 4).map(x => <div className="category-row" key={x.name}><span><i className="dot" style={{ background: categoryColors[x.name] }} />{x.name}</span><b>{money(x.value)}</b></div>)}</div></div></section>
      <section className="lower-grid"><div className="card transactions-card"><CardHeading title="Recent transactions" subtitle={`${filtered.length} transactions`} action="View all" onAction={() => setActive('Transactions')} /><div className="transaction-list">{filtered.slice(0, 5).map(t => <TransactionRow key={t.id} tx={t} onEdit={() => { setEditing(t); setModal('transaction') }} onDelete={() => setConfirmDelete(t)} />)}{filtered.length === 0 && <EmptyState text="No transactions match your filters." onClick={openNew} />}</div></div><div className="card budgets-card"><CardHeading title="Budget progress" subtitle="Monthly spending limits" action="Manage" onAction={() => setActive('Budgets')} />{budgets.map(b => { const spent = transactions.filter(t => t.type === 'expense' && t.category === b.category && new Date(t.date).getMonth() === new Date().getMonth()).reduce((s, t) => s + t.amount, 0); const percent = Math.round(spent / b.limit * 100); return <div className="budget-item" key={b.category}><div className="budget-label"><span>{b.category}</span><span className={percent > 100 ? 'over' : ''}>{money(spent)} <em>/ {money(b.limit)}</em></span></div><div className="progress"><i className={percent > 100 ? 'over' : ''} style={{ width: `${Math.min(percent, 100)}%` }} /></div>{percent > 100 && <small className="warning">Over budget by {money(spent - b.limit)}</small>}</div>})}<button className="add-budget" onClick={() => setModal('budget')}><Plus size={15} /> Add budget</button></div></section></> : <Page title={active} transactions={transactions} setActive={setActive} onAdd={openNew} budgets={budgets} setBudgets={setBudgets} accounts={accountBalances} />}
    </main>
    {modal === 'transaction' && <TransactionModal initial={editing} onClose={() => { setModal(null); setEditing(null) }} onSave={saveTransaction} />}{modal === 'budget' && <BudgetModal budgets={budgets} onClose={() => setModal(null)} onSave={b => { setBudgets(prev => [...prev.filter(x => x.category !== b.category), b]); setModal(null) }} />}{confirmDelete && <ConfirmModal tx={confirmDelete} onCancel={() => setConfirmDelete(null)} onConfirm={deleteTransaction} />}
  </div>
}

function Stat({ title, value, detail, change, icon, tone }: { title: string; value: string; detail: string; change?: string; icon: React.ReactNode; tone: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div className="stat-copy"><span>{title}</span><strong>{value}</strong><small>{change && <b className={change.startsWith('-') || change === 'Below target' ? 'negative' : 'positive'}>{change}</b>} {detail}</small></div></div> }
function CardHeading({ title, subtitle, action, onAction }: { title: string; subtitle: string; action: string; onAction?: () => void }) { return <div className="card-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onAction}>{action} <ChevronDown size={14} /></button></div> }
function TransactionRow({ tx, onEdit, onDelete }: { tx: Transaction; onEdit: () => void; onDelete: () => void }) { return <div className="transaction-row"><div className={`transaction-icon ${tx.type}`}>{tx.type === 'income' ? <ArrowDownLeft size={17} /> : <ArrowUpRight size={17} />}</div><div className="transaction-details"><strong>{tx.description}</strong><span>{tx.category} · {new Date(tx.date + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></div><div className={tx.type === 'income' ? 'transaction-amount income-text' : 'transaction-amount'}>{tx.type === 'income' ? '+' : '-'}{money(tx.amount)}</div><div className="row-actions"><button onClick={onEdit} aria-label="Edit"><Edit3 size={14} /></button><button onClick={onDelete} aria-label="Delete"><Trash2 size={14} /></button></div></div> }
function EmptyState({ text, onClick }: { text: string; onClick: () => void }) { return <div className="empty-state"><Receipt size={28} /><p>{text}</p><button onClick={onClick}>Add a transaction</button></div> }

function Page({ title, transactions, onAdd, budgets, setBudgets, accounts }: { title: string; transactions: Transaction[]; setActive: (v: string) => void; onAdd: () => void; budgets: Budget[]; setBudgets: (b: Budget[]) => void; accounts: { name: string; amount: number; icon: React.ComponentType<{ size?: number }> }[] }) { return <><section className="page-heading"><div><p className="eyebrow">Workspace</p><h1>{title}</h1><p className="subheading">{title === 'Transactions' ? 'Keep every dollar accounted for.' : title === 'Budgets' ? 'Plan ahead and spend with confidence.' : 'Your connected accounts at a glance.'}</p></div>{title === 'Transactions' && <button className="primary-button" onClick={onAdd}><Plus size={17} /> Add transaction</button>}</section>{title === 'Transactions' && <div className="card transactions-page"><div className="table-toolbar"><div className="search-box"><Search size={16} /><input placeholder="Search transactions" /></div><button className="filter-button"><Filter size={15}/> Filters</button></div>{transactions.map(t => <TransactionRow key={t.id} tx={t} onEdit={() => {}} onDelete={() => {}} />)}</div>}{title === 'Accounts' && <div className="account-grid">{accounts.map(a => { const Icon = a.icon; return <div className="card account-card" key={a.name}><div className="account-icon"><Icon size={19}/></div><span>{a.name}</span><strong>{money(a.amount)}</strong><small>Updated just now</small></div>})}<button className="add-account card"><Plus size={20}/><span>Connect an account</span><small>Cloud sync coming soon</small></button></div>}{title === 'Budgets' && <div className="budget-page-grid">{budgets.map(b => <div className="card large-budget" key={b.category}><div className="budget-label"><span>{b.category}</span><b>{money(b.limit)}<em> / month</em></b></div><div className="progress"><i style={{ width: '34%' }} /></div><p>Set a monthly limit for {b.category.toLowerCase()}.</p><button onClick={() => setBudgets(budgets.filter(x => x.category !== b.category))}>Remove budget</button></div>)}<div className="card large-budget add-large" onClick={() => {}}><Plus size={24}/><strong>Create a budget</strong><span>Choose a category and limit</span></div></div>}</> }

function TransactionModal({ initial, onClose, onSave }: { initial: Transaction | null; onClose: () => void; onSave: (t: Transaction) => void }) { const [form, setForm] = useState<Transaction>(initial || { id: String(Date.now()), date: today, type: 'expense', amount: 0, category: 'Food', account: 'Checking', description: '', recurring: false }); const update = (key: keyof Transaction, value: string | number | boolean) => setForm(f => ({ ...f, [key]: value })); const submit = (e: FormEvent) => { e.preventDefault(); if (form.amount > 0 && form.description.trim()) onSave(form) }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">{initial ? 'Edit entry' : 'New entry'}</p><h2>{initial ? 'Edit transaction' : 'Add transaction'}</h2></div><button type="button" className="close-button" onClick={onClose}><X size={19}/></button></div><div className="type-toggle"><button type="button" className={form.type === 'expense' ? 'active expense-toggle' : ''} onClick={() => update('type', 'expense')}><ArrowUpRight size={16}/> Expense</button><button type="button" className={form.type === 'income' ? 'active income-toggle' : ''} onClick={() => update('type', 'income')}><ArrowDownLeft size={16}/> Income</button></div><label>Description<input autoFocus value={form.description} onChange={e => update('description', e.target.value)} placeholder="e.g. Grocery run" required /></label><div className="form-row"><label>Amount<input type="number" min="0.01" step="0.01" value={form.amount || ''} onChange={e => update('amount', Number(e.target.value))} placeholder="0.00" required /></label><label>Date<input type="date" value={form.date} onChange={e => update('date', e.target.value)} required /></label></div><div className="form-row"><label>Category<select value={form.category} onChange={e => update('category', e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Account<select value={form.account} onChange={e => update('account', e.target.value)}>{accounts.map(a => <option key={a}>{a}</option>)}</select></label></div><label className="check-label"><input type="checkbox" checked={form.recurring} onChange={e => update('recurring', e.target.checked)} /><span>Make this a recurring transaction</span></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit"><Check size={16}/> {initial ? 'Save changes' : 'Add transaction'}</button></div></form></div> }
function BudgetModal({ budgets, onClose, onSave }: { budgets: Budget[]; onClose: () => void; onSave: (b: Budget) => void }) { const [category, setCategory] = useState(expenseCategories.find(c => !budgets.some(b => b.category === c)) || 'Food'); const [limit, setLimit] = useState(500); return <div className="modal-backdrop"><form className="modal small-modal" onSubmit={e => { e.preventDefault(); onSave({ category, limit }) }}><div className="modal-heading"><div><p className="eyebrow">Plan your month</p><h2>New budget</h2></div><button type="button" className="close-button" onClick={onClose}><X size={19}/></button></div><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{expenseCategories.map(c => <option key={c}>{c}</option>)}</select></label><label>Monthly limit<input type="number" min="1" value={limit} onChange={e => setLimit(Number(e.target.value))}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">Create budget</button></div></form></div> }
function ConfirmModal({ tx, onCancel, onConfirm }: { tx: Transaction; onCancel: () => void; onConfirm: () => void }) { return <div className="modal-backdrop"><div className="modal small-modal"><div className="delete-icon"><Trash2 size={20}/></div><h2>Delete this transaction?</h2><p className="confirm-text">“{tx.description}” will be permanently removed from your records.</p><div className="modal-actions"><button className="secondary-button" onClick={onCancel}>Keep it</button><button className="danger-button" onClick={onConfirm}>Delete</button></div></div></div> }
